### ISSUE TITLE
No static method valueOf

### ISSUE THREAD

**Issue by smyang10** [Kynetics/android-ethernet-example-app#1]
I am getting an error 

> No static method valueOf(Ljava/lang/String;)Landroid/net/IpConfiguration$IpAssignment; in class Landroid/net/IpConfiguration$IpAssignment; or its super classes (declaration of 'android.net.IpConfiguration$IpAssignment' appears in /system/framework/framework.jar)

when running

`eth.SetConfiguration("eth0", ipConf);`

in the following code:

        SystemEthernetManager eth = SystemEthernetManager.Get(context);

        List<InetAddress> dnsList = new List<InetAddress>();
        dnsList.Add(InetAddress.GetByName("8.8.8.8"));
        dnsList.Add(InetAddress.GetByName("8.8.4.4"));

        IpConfiguration ipConf = new IpConfiguration(
          IpConfiguration.IpAssignment.Static,
          new StaticIpConfiguration("192.168.0.100/24", InetAddress.GetByName("192.168.0.1"), dnsList, null),
          IpConfiguration.ProxySettings.Unassigned,
          null
          );

        eth.SetConfiguration("eth0", ipConf);

The ethernet library built successfully and the project includes the Xamarin.Kotlin.StdLib library.

**Comment by smyang10** [comment]
Due to app not being signed with platform key

**Comment by nicolalagloria** [comment]
Correct.
